name: A64
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: code
      uses: actions/checkout@v4
    - name: jdk
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: ndk
      id: setup-ndk
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r26d
    - run: sh bld.sh
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
